networks:
  nginx_net:
    driver: bridge

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net

  backend1:
    container_name: backend-1
    build: .
    volumes:
      - .:/app
    ports:
      - "8081:3005"
    environment:
      - PORT=3005
      - SERVER_NAME=backend-1
    networks:
      - nginx_net
    healthcheck:
      test: "curl http://127.0.0.1.nip.io:8080/"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
  
  backend2:
    container_name: backend-2
    build: .
    volumes:
      - .:/app
    ports:
      - "8082:3006"
    environment:
      - PORT=3006
      - SERVER_NAME=backend-2
    networks:
      - nginx_net
    healthcheck:
      test: "curl http://127.0.0.1.nip.io:8080/"
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s